# Generated by Django 4.2.16 on 2026-09-28 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("submit", "Submission — graded against hidden test cases"),
                            ("run", "Run Only — custom input, not graded"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("started", "Started by worker"),
                            ("compiling", "Compiling"),
                            ("running", "Running test cases"),
                            ("completed", "Completed"),
                            ("failed", "Failed — worker error"),
                            ("timed_out", "Timed out — worker did not respond"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("queued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("worker_id", models.CharField(blank=True, max_length=100)),
                ("error_detail", models.TextField(blank=True)),
                (
                    "run_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_job",
                        to="submissions.runrequest",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_job",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "db_table": "execution_job",
                "indexes": [
                    models.Index(
                        fields=["status", "queued_at"],
                        name="execution_j_status_4113d5_idx",
                    )
                ],
            },
        ),
    ]
