# Generated by Django 4.2.16 on 2026-09-28 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exam_sessions", "0001_initial"),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=20)),
                ("code", models.TextField()),
                (
                    "submitted_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("accepted", "Accepted"),
                            ("wrong_answer", "Wrong Answer"),
                            ("tle", "Time Limit Exceeded"),
                            ("mle", "Memory Limit Exceeded"),
                            ("compilation_error", "Compilation Error"),
                            ("runtime_error", "Runtime Error"),
                            ("ole", "Output Limit Exceeded"),
                            (
                                "internal_error",
                                "Internal Error — system issue, not student fault",
                            ),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "passed_test_cases",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "total_test_cases",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("compiler_output", models.TextField(blank=True)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("judged_at", models.DateTimeField(blank=True, null=True)),
                ("worker_id", models.CharField(blank=True, max_length=100)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="exams.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="exam_sessions.examsession",
                    ),
                ),
            ],
            options={
                "db_table": "submissions_submission",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("accepted", "Accepted"),
                            ("wrong_answer", "Wrong Answer"),
                            ("tle", "Time Limit Exceeded"),
                            ("mle", "Memory Limit Exceeded"),
                            ("compilation_error", "Compilation Error"),
                            ("runtime_error", "Runtime Error"),
                            ("ole", "Output Limit Exceeded"),
                            (
                                "internal_error",
                                "Internal Error — system issue, not student fault",
                            ),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("time_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "memory_mb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("stdout", models.TextField(blank=True)),
                ("stderr", models.TextField(blank=True)),
                ("output_matched", models.BooleanField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="submissions.submission",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="exams.testcase",
                    ),
                ),
            ],
            options={
                "db_table": "submissions_result",
                "ordering": ["submission", "test_case__order"],
            },
        ),
        migrations.CreateModel(
            name="RunRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=20)),
                ("code", models.TextField()),
                (
                    "stdin",
                    models.TextField(
                        blank=True, help_text="Custom input provided by the student"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("stdout", models.TextField(blank=True)),
                ("stderr", models.TextField(blank=True)),
                ("compiler_output", models.TextField(blank=True)),
                ("exit_code", models.SmallIntegerField(blank=True, null=True)),
                ("time_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "memory_mb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("accepted", "Accepted"),
                            ("wrong_answer", "Wrong Answer"),
                            ("tle", "Time Limit Exceeded"),
                            ("mle", "Memory Limit Exceeded"),
                            ("compilation_error", "Compilation Error"),
                            ("runtime_error", "Runtime Error"),
                            ("ole", "Output Limit Exceeded"),
                            (
                                "internal_error",
                                "Internal Error — system issue, not student fault",
                            ),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_requests",
                        to="exams.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_requests",
                        to="exam_sessions.examsession",
                    ),
                ),
            ],
            options={
                "db_table": "submissions_runrequest",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["session", "question", "-submitted_at"],
                name="submissions_session_3cb4b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["verdict"], name="submissions_verdict_223995_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runrequest",
            index=models.Index(
                fields=["session", "-requested_at"],
                name="submissions_session_a4819c_idx",
            ),
        ),
    ]
