# Generated by Django 4.2.16 on 2026-09-28 06:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instructions shown to students before the exam begins",
                    ),
                ),
                ("scheduled_start", models.DateTimeField(db_index=True)),
                ("scheduled_end", models.DateTimeField(db_index=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        help_text="Wall-clock duration of the exam in seconds. The student's personal timer starts when they enter the exam.",
                        validators=[django.core.validators.MinValueValidator(300)],
                    ),
                ),
                (
                    "allowed_languages",
                    models.JSONField(
                        default=list,
                        help_text="List of Language enum values permitted in this exam",
                    ),
                ),
                (
                    "allowed_ip_ranges",
                    models.JSONField(
                        default=list,
                        help_text="CIDR ranges that may access this exam. Empty = no restriction.",
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Minimum score to pass (optional, informational only)",
                        null=True,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Unpublished exams are invisible to students",
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["admin", "proctor"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exams_exam",
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Display order within the exam (1-indexed)"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "statement",
                    models.TextField(help_text="Problem statement (supports Markdown)"),
                ),
                ("input_format", models.TextField(blank=True)),
                ("output_format", models.TextField(blank=True)),
                ("constraints", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("sample_input", models.TextField(blank=True)),
                ("sample_output", models.TextField(blank=True)),
                ("sample_explanation", models.TextField(blank=True)),
                (
                    "time_limit_ms",
                    models.PositiveIntegerField(
                        default=2000,
                        help_text="Time limit in milliseconds",
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(30000),
                        ],
                    ),
                ),
                (
                    "memory_limit_mb",
                    models.PositiveIntegerField(
                        default=256,
                        help_text="Memory limit in megabytes",
                        validators=[
                            django.core.validators.MinValueValidator(16),
                            django.core.validators.MaxValueValidator(1024),
                        ],
                    ),
                ),
                ("marks", models.PositiveSmallIntegerField(default=10)),
                (
                    "allowed_languages",
                    models.JSONField(
                        blank=True,
                        help_text="Override exam-level language list for this question. Null = use exam setting.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exams_question",
                "ordering": ["exam", "order"],
                "unique_together": {("exam", "order")},
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_data",
                    models.TextField(help_text="stdin to feed the student's program"),
                ),
                (
                    "expected_output",
                    models.TextField(
                        help_text="Expected stdout (exact match after stripping trailing whitespace)"
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=True,
                        help_text="Hidden test cases are used for scoring but not shown to students",
                    ),
                ),
                (
                    "time_limit_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override question time limit for this specific test case",
                        null=True,
                    ),
                ),
                (
                    "memory_limit_mb",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override question memory limit for this specific test case",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Test case evaluation order (lower = first)",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Admin-facing explanation of what this test case covers",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "db_table": "exams_testcase",
                "ordering": ["question", "order"],
            },
        ),
        migrations.CreateModel(
            name="ExamEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("disqualified", "Disqualified"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exams_enrollment",
                "indexes": [
                    models.Index(
                        fields=["student", "status"],
                        name="exams_enrol_student_aee55f_idx",
                    ),
                    models.Index(
                        fields=["exam", "status"], name="exams_enrol_exam_id_43198e_idx"
                    ),
                ],
                "unique_together": {("exam", "student")},
            },
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["scheduled_start", "scheduled_end"],
                name="exams_exam_schedul_bda110_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["is_published", "is_archived"],
                name="exams_exam_is_publ_b136fa_idx",
            ),
        ),
    ]
