# Generated by Django 4.2.16 on 2026-09-28 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exam_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("tab_switch", "Tab Switch — student switched browser tab"),
                            ("window_blur", "Window Blur — browser window lost focus"),
                            ("fullscreen_exit", "Fullscreen Exit"),
                            ("fullscreen_enter", "Fullscreen Entered"),
                            ("copy_detected", "Copy Detected in exam window"),
                            ("paste_detected", "Paste Detected in editor"),
                            ("cut_detected", "Cut Detected in exam window"),
                            ("devtools_shortcut", "DevTools shortcut pressed"),
                            ("screenshot_shortcut", "Screenshot shortcut pressed"),
                            (
                                "multiple_session_attempt",
                                "Attempt to open duplicate session",
                            ),
                            ("ip_change", "IP address changed during exam"),
                            ("suspicious_user_agent", "Unexpected user-agent change"),
                            ("session_replay_attempt", "Reuse of an expired token"),
                            ("network_offline", "Student went offline"),
                            ("network_online", "Student came back online"),
                            ("admin_terminated", "Session terminated by administrator"),
                            ("exam_submitted", "Student submitted the exam"),
                            ("exam_time_expired", "Exam time expired"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("low", "Low — possibly accidental"),
                            ("medium", "Medium — warrants review"),
                            ("high", "High — likely cheating attempt"),
                            ("critical", "Critical — immediate action recommended"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("client", "Client"), ("server", "Server")],
                        default="client",
                        max_length=10,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_events",
                        to="exam_sessions.examsession",
                    ),
                ),
            ],
            options={
                "db_table": "security_event",
                "ordering": ["-timestamp"],
                "default_permissions": ("add", "view"),
                "indexes": [
                    models.Index(
                        fields=["session", "event_type"],
                        name="security_ev_session_e14ee3_idx",
                    ),
                    models.Index(
                        fields=["session", "severity"],
                        name="security_ev_session_c89832_idx",
                    ),
                    models.Index(
                        fields=["event_type", "severity", "-timestamp"],
                        name="security_ev_event_t_536733_idx",
                    ),
                ],
            },
        ),
    ]
