# Generated by Django 4.2.16 on 2026-09-28 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Computed as started_at + exam.duration_seconds. Never trust the client."
                    ),
                ),
                (
                    "last_heartbeat_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            (
                                "completed",
                                "Completed — student submitted all questions",
                            ),
                            ("timed_out", "Timed Out — time expired"),
                            ("terminated", "Terminated — admin or system action"),
                            ("disconnected", "Disconnected — student left mid-exam"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_fingerprint", models.JSONField(blank=True, default=dict)),
                ("current_question_order", models.PositiveSmallIntegerField(default=1)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="exams.examenrollment",
                    ),
                ),
            ],
            options={
                "db_table": "sessions_examsession",
            },
        ),
        migrations.CreateModel(
            name="CodeDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=20)),
                ("code", models.TextField(blank=True)),
                ("saved_at", models.DateTimeField(auto_now=True)),
                (
                    "save_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this draft has been autosaved",
                    ),
                ),
                (
                    "is_primary_language",
                    models.BooleanField(
                        default=True,
                        help_text="True for the language the student last had selected for this question",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_drafts",
                        to="exams.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_drafts",
                        to="exam_sessions.examsession",
                    ),
                ),
            ],
            options={
                "db_table": "sessions_codedraft",
            },
        ),
        migrations.AddIndex(
            model_name="examsession",
            index=models.Index(
                fields=["enrollment", "status"], name="sessions_ex_enrollm_43e99c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examsession",
            index=models.Index(
                fields=["status", "expires_at"], name="sessions_ex_status_684551_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codedraft",
            index=models.Index(
                fields=["session", "question"], name="sessions_co_session_8ffe56_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="codedraft",
            unique_together={("session", "question", "language")},
        ),
    ]
